queue_rules:
  - name: default
    queue_conditions:
      - base=master
      - author=scala-steward
      - check-success=Build
      - check-success=Lint
    merge_conditions:
      - check-success=Build
      - check-success=Lint
    merge_method: squash

pull_request_rules:
  - name: merge using the merge queue
    conditions: []
    actions:
      queue:
